import { Poppins } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/provider/NextAuthProvider";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "DevInsight",
    template: "%s | DevInsight",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className={`${poppins.className} antialiased bg-blue-50`} suppressHydrationWarning={true}>
          {children}
        </body>
      </html>
    </NextAuthProvider>
  );
}
